export const GETALL_BOOKING_REQUEST = "GETALL_BOOKING_REQUEST"
export const GETALL_BOOKING_SUCCESS = "GETALL_BOOKING_SUCCESS"
export const GETALL_BOOKING_FAIL = "GETALL_BOOKING_FAIL"

export const CLEAR_ERROR = "CLEAR_ERROR"