export const ALL_DETAIL_REQUEST = "ALL_DETAIL_REQUEST"
export const ALL_DETAIL_SUCCESS = "ALL_DETAIL_SUCCESS"
export const ALL_DETAIL_FAIL = "ALL_DETAIL_FAIL"

export const ADD_CAR_REQUEST = "ADD_CAR_REQUEST"
export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS"
export const ADD_CAR_FAIL = "ADD_CAR_FAIL"
export const ADD_CAR_RESET = "ADD_CAR_RESET"

export const GETSINGLE_CAR_REQUEST = "GETSINGLE_CAR_REQUEST"
export const GETSINGLE_CAR_SUCCESS = "GETSINGLE_CAR_SUCCESS"
export const GETSINGLE_CAR_FAIL = "GETSINGLE_CAR_FAIL"

export const UPDATE_CAR_REQUEST = "UPDATE_CAR_REQUEST"
export const UPDATE_CAR_SUCCESS = "UPDATE_CAR_SUCCESS"
export const UPDATE_CAR_FAIL = "UPDATE_CAR_FAIL"
export const UPDATE_CAR_RESET = "UPDATE_CAR_RESET"

export const DELETE_CAR_REQUEST = "DELETE_CAR_REQUEST"
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS"
export const DELETE_CAR_FAIL = "DELETE_CAR_FAIL"
export const DELETE_CAR_RESET = "DELETE_CAR_RESET"

export const CLEAR_ERROR = "CLEAR_ERROR"
